name: PyCOLMAP build and publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  release:
    types: [ published, edited ]
  workflow_dispatch:

jobs:
  mac-build:
    name: Wrapper macOS Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11 ]
        pyversion: ["python@3.10" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build the macOS wheels
        run: |
          ./package/build-wheels-macos.sh ${{ matrix.pyversion }}
      - name: Archive wheels
        uses: actions/upload-artifact@v3
        with:
          name: pycolmap-${{ matrix.pyversion }}-${{ matrix.os }}
          path: ./wheelhouse/pycolmap-*.whl